### ISSUE TITLE
KeyError on list_tasks

### ISSUE THREAD

**Issue by Innixma** [openml/openml-python#1234]
#### Description

OpenML crashes during list_tasks call.

It was working correctly 1 week ago.
I first noticed the error on March 25th when running a script to generate a task metadata file locally.

I've reproduced the error both on an ubuntu EC2 instance and locally on my Mac laptop.

#### Steps/Code to Reproduce

```python3
import openml
tasks = openml.tasks.list_tasks()
```

#### Exception

```
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openml/tasks/functions.py", line 273, in __list_tasks
    task[input["@name"]] = proc_dict[int(input["#text"])]["name"]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/code/scratch/scratch2.py", line 2, in <module>
    tasks = openml.tasks.list_tasks()
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openml/tasks/functions.py", line 180, in list_tasks
    return openml.utils._list_all(
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openml/utils.py", line 272, in _list_all
    new_batch = listing_call(
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openml/tasks/functions.py", line 222, in _list_tasks
    return __list_tasks(api_call=api_call, output_format=output_format)
  File "/home/ubuntu/.conda/envs/code/lib/python3.8/site-packages/openml/tasks/functions.py", line 291, in __list_tasks
    raise KeyError("Invalid xml for task %d: %s\nFrom %s" % (tid, e, task_))
KeyError: "Invalid xml for task 361346: 0\nFrom {'oml:task_id': '361346', 'oml:task_type_id': '1', 'oml:task_type': 'Supervised Classification', 'oml:did': '554', 'oml:name': 'mnist_784', 'oml:status': 'active', 'oml:format': 'ARFF', 'oml:input': [{'@name': 'estimation_procedure', '#text': '0'}, {'@name': 'source_data', '#text': '554'}, {'@name': 'target_feature', '#text': 'class'}], 'oml:quality': [{'@name': 'MajorityClassSize', '#text': '7877.0'}, {'@name': 'MaxNominalAttDistinctValues', '#text': '10.0'}, {'@name': 'MinorityClassSize', '#text': '6313.0'}, {'@name': 'NumberOfClasses', '#text': '10.0'}, {'@name': 'NumberOfFeatures', '#text': '785.0'}, {'@name': 'NumberOfInstances', '#text': '70000.0'}, {'@name': 'NumberOfInstancesWithMissingValues', '#text': '0.0'}, {'@name': 'NumberOfMissingValues', '#text': '0.0'}, {'@name': 'NumberOfNumericFeatures', '#text': '784.0'}, {'@name': 'NumberOfSymbolicFeatures', '#text': '1.0'}]}"

```

#### Versions

Ubuntu EC2 Instance

```
Linux-5.15.0-1017-aws-x86_64-with-glibc2.10
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0]
NumPy 1.23.5
SciPy 1.10.1
Scikit-Learn 1.1.1
OpenML 0.13.1
```

MacOS Laptop

```
macOS-10.16-x86_64-i386-64bit
Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58) 
[Clang 6.0 (clang-600.0.57)]
NumPy 1.22.4
SciPy 1.8.1
Scikit-Learn 1.1.1
OpenML 0.12.2
```

**Comment by LennartPurucker** [comment]
Heyho,

Thank you for the bug report! 
I was able to reproduce the problem. 

## Reason 
This is likely related to the server state, as this crashes only for the official server but not the test server. 
Moreover, the server cannot find (or display) the responsible task either (https://www.openml.org/search?type=task&id=361346). 
The task seems to employ the estimation procedure "0". This should not be allowed/possible as the list of available procedures starts at "1" (https://api.openml.org/api/v1/json/estimationprocedure/list). In fact, when running my code below, there are a lot of (recently created) tasks with this estimation procedure.

@PGijsbers do you know more about this new (not officially documented) procedure? Can we change the server's state? 

## Workaround 
A potential workaround for now and future problems like this could be to skip bad tasks instead of crashing. 
Code for that: 
Replace the following in `openml/tasks/functions.py` (Line 289-293)
```python
  except KeyError as e:
      if tid is not None:
          raise KeyError("Invalid xml for task %d: %s\nFrom %s" % (tid, e, task_))
      else:
          raise KeyError("Could not find key %s in %s!" % (e, task_))
```

with:
```
except KeyError as e:
    if tid is not None:
        warnings.warn("Invalid xml for task %d: %s\nFrom %s" % (tid, e, task_))
    else:
        warnings.warn("Could not find key %s in %s!" % (e, task_))
    continue
```

(I can create a PR/branch for this if anyone needs this to be pip installable) 

## Fix
Either we add our workaround above, or we determine why the server produces this new procedure and avoid it.
Technically, openml-python follows the specifications produced by the server - perhaps too strictly, as this crashes even though we might not need to crash in such a case.

**Comment by Innixma** [comment]
Thanks @LennartPurucker, the temporary work-around you mentioned unblocked me for now, that was very useful!

**Comment by joaquinvanschoren** [comment]
Indeed, all tasks 361346 - 361410 have estimation_procedure = 0, they are all created by the same user.
I guess they were created by accident. Shall I remove them and contact the user?

@PGijsbers @mfeurer can we also hot-patch the Python API with Lennarts failsafe?

**Comment by joaquinvanschoren** [comment]
I have now removed the broken tasks.
Listing tasks works again.

**Comment by joaquinvanschoren** [comment]
@PGijsbers Can you make a note to check for such invalid tasks in the new API? Also, we should assess the speed of this function in the new API. It currently takes 30s to return.
