### ISSUE TITLE
dataset 373 doesn't download / parse

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#129]

**Comment by amueller** [comment]
some more:

UNIX_user_data
373
ERROR
SyskillWebert-BioMedical
374
ERROR
SyskillWebert-Sheep
376
ERROR
synthetic_control
377
SyskillWebert-Goats
379
ERROR
SyskillWebert-Bands
380
ERROR

**Comment by mfeurer** [comment]
With the changes from #150 I can download dataset 377.

The others fail because one of the attributes is actually of type string. Since we're downloading a description of the dataset features anyway, we could actually first download the features and then decide to not download and parse the arff file.
