### ISSUE TITLE
KeyError on pipeline upload

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#187]
Simple pipeline experiment:
```
from sklearn import pipeline, ensemble, preprocessing
from openml import tasks,runs, datasets
task = tasks.get_task(59)
pipe = pipeline.Pipeline(steps=[
            ('Imputer', sklearn.preprocessing.Imputer(strategy='median')),
            ('OneHotEncoder', sklearn.preprocessing.OneHotEncoder(sparse=False, handle_unknown='ignore')),
            ('Classifier', sklearn.ensemble.RandomForestClassifier())
           ])
run = runs.run_task(task, pipe)
response = run.publish()
```

Error:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-7-bbc4e8d1aa68> in <module>()
      9 run = runs.run_task(task, pipe)
     10 #vars(run)
---> 11 response = run.publish()

/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/runs/run.py in publish(self)
    137 
    138         predictions = arff.dumps(self._generate_arff_dict())
--> 139         description_xml = self._create_description_xml()
    140 
    141         file_elements = {'predictions': ("predictions.arff", predictions),

/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/runs/run.py in _create_description_xml(self)
    164         downloaded_flow = openml.flows.get_flow(self.flow_id)
    165 
--> 166         openml_param_settings = _parse_parameters(self.model, downloaded_flow)
    167 
    168         # as a tag, it must be of the form ([a-zA-Z0-9_\-\.])+

/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/runs/run.py in _parse_parameters(model, flow)
    200         if isinstance(python_param_settings[param], BaseEstimator):
    201             # extract parameters of the subflow individually
--> 202             subflow = flow.components[param]
    203             openml_param_settings += _parse_parameters(python_param_settings[param], subflow)
    204 

KeyError: 'Imputer'
```

Am I doing something wrong?

**Comment by mfeurer** [comment]
Thanks for letting us know. Which branch is this on? We will then incorporate this to the unit tests.

**Comment by joaquinvanschoren** [comment]
This is for branch feature/upload-run.

**Comment by mfeurer** [comment]
Okay, that branch is still under development. There are no guarantees that it works yet.

**Comment by joaquinvanschoren** [comment]
The exact same errors happens on the master branch.
Is this way of defining a pipeline incorrect?

**Comment by mfeurer** [comment]
The pipeline looks correct. On the master branch it won't work, because the master branch can't handle pipelines yet.

**Comment by joaquinvanschoren** [comment]
Sorry, the same error pops up on develop and feature/upload-flow as well.
Anything else you want me to try?

**Comment by mfeurer** [comment]
Hm, thanks, but that's all the branches we have at the moment. It seems like this feature doesn't work yet.

**Comment by joaquinvanschoren** [comment]
Correction, I forgot to reinstall after switching branches. New information:

Feature/run-upload branch: KeyError as shown above
Develop branch: TypeError: run_task fails while checking whether the flow exists
```
Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/runs/functions.py in run_task(task, model)
     42 
     43     flow = OpenMLFlow(model=model)
---> 44     flow_id = flow._ensure_flow_exists()
     45     if (flow_id < 0):
     46         print("No flow")

/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/flows/flow.py in _ensure_flow_exists(self)
    110 
    111         if int(flow_id) == -1:
--> 112             return_code, response_xml = self.publish()
    113 
    114             response_dict = xmltodict.parse(response_xml)

TypeError: 'OpenMLFlow' object is not iterable
```

master and Feature/flow-upload branch: OpenMLServerError (Invalid XML):
```
/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/_api_calls.py in _perform_api_call(call, file_dictionary, file_elements, add_authentication)
     42     if file_dictionary is not None or file_elements is not None:
     43         return _read_url_files(url, file_dictionary=file_dictionary,
---> 44                                file_elements=file_elements)
     45     return _read_url(url)
     46 

/Users/joa/anaconda/lib/python3.5/site-packages/openml-0.3.0-py3.5.egg/openml/_api_calls.py in _read_url_files(url, file_dictionary, file_elements)
     76     response = requests.post(url, data=data, files=file_elements)
     77     if response.status_code != 200:
---> 78         raise OpenMLServerError(response.text)
     79     if 'Content-Encoding' not in response.headers or \
     80             response.headers['Content-Encoding'] != 'gzip':

OpenMLServerError: OpenML Server error: <oml:error xmlns:oml="http://openml.org/openml">
	<oml:code>202</oml:code>
	<oml:message>Could not validate run xml by xsd</oml:message>
		<oml:additional_information>XML does not correspond to XSD schema. </oml:additional_information>
	</oml:error>
```

Is the TypeError something that is fixed in `upload-run`? Hence, the main problem is the KeyError?

**Comment by mfeurer** [comment]
It's definitively fixed in one of the branches. The issue is that something goes wrong when creating the parameters for the run upload. The key error is the symptom that we can observe.

**Comment by joaquinvanschoren** [comment]
Thanks. I'll take a look and see if I can find the problem.
Btw, it seems like all uploaded pipelines are called 'sklearn.pipeline.Pipeline'. Do you have a plan to generate more readable names? (I saw something about that in a PR I think)?

**Comment by mfeurer** [comment]
I'm not sure if it's a good investment of time if you debug a PR which is based on a different PR. The names are basically a concatenation of all elements inside the pipeline. Maybe it would actually help to have the classifier in the first place?

**Comment by joaquinvanschoren** [comment]
Well, I have some students trying it out right now so wanted to see if it can be easily fixed.

Turns out the KeyError is easily fixed. 
in `run.py`, line 202, it checks for a component called 'Classifier', while it is called 'step__Classifier' in the flow. It's solved by replacing the line like this:
```
subflow = flow.components['steps__'+param]
```
But I guess you want to remove the 'steps__' prefix from the flow component names in the first place?

Anyway, this fixes the problem, but then another problem shows up. In the XML run description, the top-level workflow has a parameter 'Classifier', but in the uploaded flow there is only a parameter 'steps' with a JSON string: http://www.openml.org/f/4976

Does that make sense? I guess there is a problem with uploading the top-level flow?

**Comment by mfeurer** [comment]
I'm sorry to say, but pipelines should not be uploaded at all at the moment. There is no guarantee that one will be able to read the uploaded output in a week/month/year. Also, branches except the master branch should not be actively used. I'll try to have a look at the general problem this week (although I can't guarantee anything).

**Comment by janvanrijn** [comment]
Many nested flows worked before, but I'm not sure about the pipeline. 

In the connector we now rely on the fact that in the case of nested flows, the parameters follow the convention subflowname__parametername or subflowname__subsubflowname__parametername
Upon this assumption we built the function that links parameters values to parameters, which in it's turn assumes that if a parameter value is a 'BaseEstimator', this is reflected in the flow object (by having a component in there with the exact same name)

Now, in the case of Pipelines, the following happens. Somewhere in the flow creation code (the function that converts a sklearn object into an openml flow object) it does correctly create the pipeline with its components, however it does add the prefix "steps__" to every component (probably because steps is a list of Estimators?)

So, either the run module has to be informed that Pipelines are special objects and therefore traverse the submodels differently, or the flow generation needs to be adapted to create pipelines that have subcomponents without the 'steps__' prefix. i.e., the following flow:
http://capa.win.tue.nl/f/9750 (sklearn.pipeline.Pipeline(steps__ohe=sklearn.preprocessing.data.OneHotEncoder,steps__scaler=sklearn.preprocessing.data.StandardScaler,steps__fu=sklearn.pipeline.FeatureUnion(transformer_list__pca=sklearn.decomposition.truncated_svd.TruncatedSVD,transformer_list__fs=sklearn.feature_selection.univariate_selection.SelectPercentile),steps__boosting=sklearn.ensemble.weight_boosting.AdaBoostClassifier(base_estimator=sklearn.tree.tree.DecisionTreeClassifier)))
would become:
sklearn.pipeline.Pipeline(ohe=sklearn.preprocessing.data.OneHotEncoder,scaler=sklearn.preprocessing.data.StandardScaler,fu=sklearn.pipeline.FeatureUnion(transformer_list__pca=sklearn.decomposition.truncated_svd.TruncatedSVD,transformer_list__fs=sklearn.feature_selection.univariate_selection.SelectPercentile),boosting=sklearn.ensemble.weight_boosting.AdaBoostClassifier(base_estimator=sklearn.tree.tree.DecisionTreeClassifier))

@mfeurer we can talk tomorrow in detail :)

**Comment by joaquinvanschoren** [comment]
Is this issue still open? I do still get a key error when uploading pipelines. Can we look at this on Monday?

**Comment by janvanrijn** [comment]
Matthias did the update required by my comment on Feb 1 a while ago, enabling me to fix this issue. Currently trying to merge the fix.

**Comment by janvanrijn** [comment]
Merged a fix on develop branch. Only 5/6 server checks seem to pass. Any clue on the last one? Seems like something completely random popped up?

**Comment by joaquinvanschoren** [comment]
Original error is fixed. Tests are passing.
