### ISSUE TITLE
Retrieving class labels of a dataset

### ISSUE THREAD

**Issue by PG-TUe** [openml/openml-python#25]
I'm working on a function which lets users more easily run machine learning experiments through the OpenML API. For every run, the arff-file which contains the result should contain the names of the class labels. Currently there is no way to directly retrieve class labels from an OpenML dataset object.

In the code below, let's assume that 'dataset' is an OpenML Dataset entity of the [iris dataset](http://www.openml.org/d/61), so it should have the class labels {Iris-setosa,Iris-versicolor,Iris-virginica}.
What I would like is (something like) this:
```
dataset.class_labels
>>> ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]
```
Instead, I currently do this (which works):
```
arffFileName = dataset.data_file;
with open(arffFileName) as fh:
    arffData = arff.ArffDecoder().decode(fh);
    dataAttributes = dict(arffData['attributes']);
dataAttributes['class'];
```
That is, I open the associated ARFF file, and decode it to find the class label information. After executing above code, dataAttributes['class'] is exactly  ["Iris-setosa", "Iris-versicolor", "Iris-virginica"].

At first I thought I would simply change the initialization of the dataset, and add a class_label attribute, but looking into it raised the following questions:
 -  In [apiconnector.py line 456](https://github.com/openml/python/blob/feature/script/openml/apiconnector.py#L456), which currently initializes the dataset objects, the dataset description is used to initialize the dataset object. Class labels are not information contained in the dataset description XML file, but instead in the data ARFF file. This means that in order to retrieve the class labels, the ARFF file has to be opened. First, this seems to clash with the design so far, in that the dataset can be constructed from the description alone (and if the dataset ARFF is already cached, it then does not need to be opened). Second, from the comment on  [apiconnector.py line 536](https://github.com/openml/python/blob/feature/script/openml/apiconnector.py#L536) I gather that ARFF files might be sufficiently large not to want to load them into memory if not necessary. Opening a potentially colossal file just to search for the class labels attribute might be too much overhead, though since the attributes are listed before the data, I think a lazy read might negate much of the overhead. So should the class labels be stored in the description, or should the ARFF file be read upon construction of the dataset?
 -  Not all datasets have class labels (for example unsupervised learning problems), so in that sense it is not a generic dataset property. For those datasets, I'm in favor of just setting class_labels to None, but perhaps there are reasons to instead return an empty list. Alternatively, this could be an argument against having a class_label property.

If we can reach a conclusion, then I will try to implement it on my feature branch (feature/script (which I admit is poorly named and will rename to feature/run or feature/autorun)). Looking forward to hearing your thoughts.

Kind regards,
Pieter Gijsbers

**Comment by mfeurer** [comment]
Hi Pieter,
as you found out, the datasets is initialized from the dataset description, but it also read in the .arff file at creation time. Thus, it would be possible to such a flag. I'm not sure if this would be the way to go, because for example regression doesn't have names as well.

For that I would advocate that you read the header of the file in order to find out about the class attribute as you already proposed. Reading only the attributes should be fast enough. And if there are many of them, training the ML algorithm should nevertheless take much longer;)

In practice, you can have a look at the liac-arff repository and add another flag there which is called read_attributes.

Does that make sense to you?

**Comment by PG-TUe** [comment]
>  but it also read in the .arff file at creation time

Are you referring to [this line](https://github.com/openml/python/blob/feature/script/openml/apiconnector.py#L477)? 

As the content of the arff file is removed from memory in function download_dataset_arff, if you want to double dip you will also have to extract class labels inside the download_dataset_arff function. Alternatively, we could re-open the arff file after download_dataset_arff to then extract additional information (such as the class label), and initialize the dataset object with that additional information.

What would be preferred?

If needed, I will look into opening an issue at the liac-arff repo (or if I find the time, create a pull request myself).

**Comment by joaquinvanschoren** [comment]
Interesting issue. I guess that the only reason you need the class labels
is for returning the predictions (the class confidences)? Hence, you do not
want to actually open the dataset.
Is there another reason?

The reason that class labels are not returned by the dataset API is that
there is not always a clear definition of what a target actually is. There
can be zero, one or multiple targets intended, and the types can be
different. What would make more sense is to include them in the task API,
since there the target is defined by the creator of that task. We have the
labels in our database.

Ultimately, this makes a lot of sense. Right now we are only dealing with
ARFF, but what if in the future we have to deal with CSV or HDF? If we
handle this on the server, we can return a uniform representation to the
interfaces. The interfaces would still need to to include different readers
for different data formats, but not worry about how to extract the class
labels from them. Maybe the readers (such as arff) have support for this,
but this may not be true for all readers.

Would it help you if we add the labels to the task description? I cannot
promise that we will do this very soon, but if you go for an interim
solution by reading the ARFF files, please take into account that this
should happen on the level of tasks, not datasets. For this, it makes sense
that the dataset is part of the task, this is also how it is done in the R
and Java interfaces.

**Comment by mfeurer** [comment]
I would go one step further than Joaquin and say that even a task does not need to know the labels. From what I understand, only the run object needs to know the label. In practice, the run object would get the labels from the task. Thus, the classification task object should implement that functionality.

For now, I would suggest that you add a callback to the liac-arff main loop. Then you can check whether the attributes are already read and stop parsing at that point.

**Comment by PG-TUe** [comment]
Yea, I only need the class labels because I need to put them in the predictions arff file. Internally (during prediction/evaluation), classes are represented by numeric values anyway.

Your arguments have convinced me that class labels should be in a task, not a dataset (though the issue remains that not all tasks are classification tasks). For now, the best I can think of is setting a class_label attribute to either a list of strings representing the class names if the arff file contains a class attribute, and None otherwise.

>For now, I would suggest that you add a callback to the liac-arff main loop.

As in actually editing liac-arff ([this loop](https://github.com/renatopp/liac-arff/blob/master/arff.py#L633))? That could be nice, though I'm currently doing this as part of a school project. I might have to limit my scope in order to make sure everything is done in time, so I will probably first just read the entire file and collect the class labels - so that it can be improved at a later time.

**Comment by mfeurer** [comment]
I assume that we will have separate class objects for classification, regression etc. at some point. Don't worry about this now.

And yes, you've got the correct loop.

**Comment by mfeurer** [comment]
Since this feature request also came up in #35 I've created a [way to find out class labels in this branch](https://github.com/openml/python/tree/feature/class_labels). Does this help you?

**Comment by PG-TUe** [comment]
From the code it is not immediately clear to me, but I think it might help. I'll try to look into it (but that will be thursday or later). Thanks!

**Comment by mfeurer** [comment]
If you call the the method `dataset.get_dataset()` with the arguments `class=` and `return_attribute_labels=True`, it will return a list of dicts for the X and y array, which map from attribute IDs to the labels. For the y array, the labels of IDs are the class labels.

**Comment by joaquinvanschoren** [comment]
Cool, so we can do that for any class? Also for a non-default class?

**Comment by mfeurer** [comment]
Yes. If an attribute is numerical, there will be a None instead of a dict; for a nominal attribute there will be a dict. This seems to be a general solution on the dataset level, which can then be used for more general functionality on the task level, for example in an upcoming classification task.

**Comment by PG-TUe** [comment]
I'm not 100% sure, but I think something is wrong with my install.

When I installed from master, I get the error that return_attribute_labels was not expected (which is correct- it is in the feature branch). I then switched to the feature branch, ran the install again, which now gives me: `ValueError` need more than 3 values to unpack [at line 144](https://github.com/openml/python/blob/feature/class_labels/openml/entities/dataset.py#L144). Is it possible that this has to do with me using Python 2.7.11 (and thus at most Pickle 2.0)?

Looking at the code more, I think it would do what I want it to do, but I can't verify right now because of the above issue.

**Comment by mfeurer** [comment]
The issue here is that you try to load cached pickle files which were generated with the old code which saved a tuple of length three in the pickle. The new code assumes a tuple of length four. Thus, you have delete all pickle files when you change between these branches.

**Comment by joaquinvanschoren** [comment]
Sounds indeed like a stale pickle problem. Close?

**Comment by PG-TUe** [comment]
Sorry, I checked it and it was indeed the caching. Closed.
