### ISSUE TITLE
runs.get_run(RUN_ID) raises ValueError for multiple run_ids

### ISSUE THREAD

**Issue by minoriinoue** [openml/openml-python#309]
Hi,

I get:
> ValueError: No prediction files for run 615362 in run description XML

for multiple run_ids which I fetched from runs.list_runs().
(E.g. run_id: 1501000, 828338, 1713943, 1316827, 1255539, 1253179, 1499134, 615362)

I used task_id = 54727, flow_id = 4221 this time. Didn't check with other task, flow ids.

I checked if those runs exist with OpenML REST API [here](https://www.openml.org/api_docs/#!/run/get_run_id), and it returns fine.
Reading code in runs/functions.py, I thought it might be a cache problem (#308),
so I did:
`rm -r ~/.openml/cache`

Now I have:
>  [Errno 2] No such file or directory: '~/.openml/cache/runs/run_1501000.xml'

Am I doing something wrong?

Best,
Minori

**Comment by janvanrijn** [comment]
As far as I am concerned, you are not doing anything wrong.

Some results on OpenML do not contain description XML (old error). These
runs should not be used (as these obviously do not have any evaluations
attached). The OpenML python api should handle these problems more
gracefully. Will push a fix soon.

Until that time, you are advised to use the evaluation list function,
pointing only to runs that were able to be evaluated (and hence are
guaranteed to be valid.)

2017-09-20 11:23 GMT+02:00 Minori Inoue <notifications@github.com>:

**Comment by minoriinoue** [comment]
Got it! Thanks!

**Comment by minoriinoue** [comment]
Just a quick question - it seems you need to filter by "functions" if you want to list evaluations using python client.
Does that mean I cannot list all evaluations like I list runs by runs.list_runs?

Or I should make get request with raw api url because it seems like I can list evaluations without function [here](https://www.openml.org/api_docs/#!/evaluation/get_evaluation_list_filters).

**Comment by janvanrijn** [comment]
Personally, I found the evaluation api pretty annoying when it returns
multiple evaluation metrics per run. Thats why I implemented it this way.
You can indeed use the raw url, but note that (due to query optimization)
for every run multiple 'blocks' will be returned.

My advise: If you need all evaluations, iterate over all runs individually
(should be fast once they are cached)

2017-09-20 16:06 GMT+02:00 Minori Inoue <notifications@github.com>:

**Comment by minoriinoue** [comment]
Iterate over all run_ids given by runs.list_runs() and runs.get_run(),
then catch the error when there's no evaluation? That's what you meant?

**Comment by mfeurer** [comment]
The issue is basically that we don't support the [subgroup discovery task](https://www.openml.org/tt/8) in python. The runs which you are trying to load are on such tasks (and the runs try to load the tasks) which is why it failed. The latest development branch version gives a nice error for this:

```python
import openml

for run in [1501000, 828338, 1713943, 1316827, 1255539, 1253179, 1499134, 615362]:
    try:
        openml.runs.get_run(run)
    except Exception as e:
        print(e)
```
which gives the output:
```
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
Task type Subgroup Discovery not supported.
```
Please open a new issue if you want to propose the Python API to implement subgroup discovery.
