### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#407]
I heard from some people that they have difficulties installing openml-python on Windows.
The problem is that one of the dependencies requires a C compiler to install, so it tells people that they need to install the Visual C Build Tools first. The message is somewhat hidden in the output, though.

The problematic dependency seems to be 'netifaces'. The error you get is basically the first error shown here: https://github.com/mirko/SonOTA/issues/61

Is 'netifaces' a strict dependency or can we get rid of it? 
Is it part of cython and if so do we really need cython?

Thanks!

**Comment by mfeurer** [comment]
This package isn't a direct dependency of openml-python. It's a dependency of `oslo.concurrency`, which is necessary to avoid race conditions when writing files from multiple processes. One could potentially use a different locking library, but I'm not an expert here. In order to ensure OpenML working on Windows, it would be good to set up a CI system for Windows.

**Comment by joaquinvanschoren** [comment]
CI for Windows is a great idea.
Don't know too much about other locking libs either. Maybe the 'treading' package?

Is it possible to specify a different installation path for Windows? It seems you can replace netifaces
with a precompiled binary installed by pip:
https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

For netifaces this can be found here:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

That should also solve it?

**Comment by joaquinvanschoren** [comment]
I would love to help, but don't own a Windows machine (nor have access to one). I just heard about this issue from students.

IIUC, that means that this is only an issue for python>3.6? Will have to test that...
A simple fix would be to ask people to first git install netifaces using the precompiled binary.

**Comment by joaquinvanschoren** [comment]
What would be the easiest way to install the openml library? Right now, the documentation says to clone from git and run the setup manually.

In my experience, this also works well:
```
pip install git+https://github.com/openml/openml-python.git@develop
```

Is there a reason not to recommend this?

**Comment by mfeurer** [comment]
Actually that's also what I'm using and we should probably recommend that in the user guide. However, I'm not sure what happens if you don't have wheel installed and do this in an empty repository (will it then start installing all dependencies one after the other?).

Another potential solution to the overall problem is installing a compiler. Instead of using visual studio, one could also use the compiler shipped with AnaConda (under the assumption your students use AnaConda).

**Comment by PGijsbers** [comment]
I tried to work on this, but the internet connection here doesn't play nicely with the Windows VM I was trying to configure to reproduce the issue. I'll probably work on this when I have access to a good, wired, connection.

**Comment by PGijsbers** [comment]
Closing this issue as:
 - installation guide now specifies to install through pip (even from code) with `pip install -e .` which should install dependencies correctly regardless of platform.
 - the main culprit `oslo.concurrency` is no longer a dependency (for non-developers)
 - CI on Windows has been running fine for a year now.
