### ISSUE TITLE
Get all computed qualities (metafeatures) for a dataset

### ISSUE THREAD

**Issue by jetsnguns** [openml/openml-python#413]
Right now only a small portion of qualities are returned for each dataset after a call to `list_datasets`. Is it possible to get all computed qualities for the dataset that are listed in the web interface?

**Comment by mfeurer** [comment]
`list_datasets` is a python function showing the output of this [API call](https://www.openml.org/api_docs#!/data/get_data_list). As the server does not return more meta-features this is not possible (also because the server already returns several MBs of xml). You can download each [dataset](https://github.com/openml/openml-python/blob/master/openml/datasets/dataset.py) and retrieve them via the qualities attribute of the class.

**Comment by jetsnguns** [comment]
Thanks! I'll use this approach.
