### ISSUE TITLE
A large number of dependencies

### ISSUE THREAD

**Issue by rth** [openml/openml-python#531]
When using this package during the sprint, my impression was that a large number of mandatory (and possibly unused) dependencies need to be installed for this package. 

In particular for mandatory dependencies,
 - matplotlib seems to be only used in one test (https://github.com/openml/openml-python/issues/530)
 - nbformat is only used in one test `tests/test_examples/test_OpenMLDemo.py`
 - the `nose` and `mock` packages are only needed for tests. And with pytest, mock will no longer be needed.
 - `oslo.concurrency` is only used in tests

for extra test dependencies,
 - couldn't find any imports of the installed `jupyter_client`

I probably missed a few things.

**Comment by mfeurer** [comment]
I agree that this package has a lot of dependencies. Regarding your comments:

* matplotlib: can be removed - see my answer in #530 
* nbformat can be removed because of the same reason
* we will be able to remove mock once we drop python2 support. I don't think it is realistic that we will find time to refactor the unit tests to no longer use mock, though. Nevertheless, does pytest include a replacement for mock?
* oslo.concurrency is for locking the cache. It might indeed only be used for the unit tests (to run them in parallel), but can also be useful during regular development
* jupyter* can probably removed as we currently do not need it for testing, most likely only for bulding the documentation.

**Comment by PGijsbers** [comment]
With many issues open on the same topic, I decided to close this one. All further discussion can be had in #596.
