### ISSUE TITLE
Separate interaction with API into a dedicated package

### ISSUE THREAD

**Issue by KOLANICH** [openml/openml-python#596]
#### Description
`openml` package has to many dependencies, if I just want to do some interaction with API, I don't need them all.

**Comment by nok** [comment]
Which ones?

**Comment by KOLANICH** [comment]
https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/setup.py#L47
https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/setup.py#L44
are used only in flows and are unneeded for fetching datasets via API. Though it may make sense to create a separate package dedicated to interaction wjth api with minimum of dependencies.

https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/setup.py#L45
https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/setup.py#L37
are used only in tests and should be moved to 
https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/setup.py#L50

**Comment by nok** [comment]
Yes, I agree. In addition the unit tests should be excluded for a release.
https://github.com/openml/openml-python/blob/master/setup.py#L35

**Comment by mfeurer** [comment]
A few brief comments:
* oslo.concurrency: Necessary to use the OpenML connector multiple times in parallel. However, if there are any better locking tools with less dependencies I'd be happy to accept a PR which changes this. I chose oslo back then because it's the successor of [lockfile](https://pypi.org/project/lockfile/).
* scikit-learn: I can see your point here, but for now this has the huge advantage of having lots of integration tests. Also, in my opinion this would create more short term work than benefits.
* nbformat, mock and test: happy to accept a pull which moves them to test.

**Comment by PGijsbers** [comment]
I agree it's important to take a look at which packages should be required, and which can be sorted in `extra_requires` or dropped altogether.
Because there are multiple open issues with this sentiment, I will close all of them except for this one.
Other issues which have a discussion on dependencies:
 - #530
 - #531

**Comment by PGijsbers** [comment]
Test-only dependencies have now been marked as such, when installing `openml-python`, by default `oslo.concurrency` is no longer a dependency. See #675.
