### ISSUE TITLE
nice repr for all classes

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#75]

**Comment by mfeurer** [comment]
Added via #701.

**Comment by amueller** [comment]
actually not true, you added ``__str__`` not ``__repr__``, which is what ipython uses. So it's not helping for notebooks.
If you don't like changing ``__repr__`` you can do ``_repr_pretty_``.

**Comment by Neeratyoy** [comment]
Hi @amueller,
I have a [branch](https://github.com/openml/openml-python/tree/add_repr) ready with the changes that you suggested. I'll create a PR once I get a green light.

The current design has been tested on ipython console, and jupyter notebooks. 
`t = openml.tasks.get_task(31) `
`t  # same output as below`
`print(t)  # same output as above`

Hope that this is the expected behaviour.

**Comment by mfeurer** [comment]
This is now closed via #743.
