### ISSUE TITLE
Evaluate the usage of black for more automatic code formatting

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#781]
https://pypi.org/project/black/

**Comment by PGijsbers** [comment]
I've been using `black` in GAMA now since a few weeks. The experience has been good so far. I also took the time to set up a [pre-commit](https://pre-commit.com/) hook. Before doing any commit (locally), it will run `black`, `mypy` and  `flake8`. The pre-commit has a few benefits:
 - You don't have to call `black` manually, so it can't be forgotten.
 - You won't have check-ins with `flake8` and `mypy` errors, which means also no commits that are just "Fix Flake8/mypy". Keeps a cleaner commit history and puts less strain on CI servers.
 - If we add configuration files for each of those packages, alongside the pre-commit configuration, everyone runs the same version of the packages with the same configurations. There will be no need for manual setup beyond `pre-commit install`.

Thoughts?

It shouldn't take a long time to set up, and I'm willing to do that. But I won't have time for it until sometime in May.

**Comment by mfeurer** [comment]
> Thoughts?

That sounds great.

> I'm willing to do that.

That's great, too :)

> But I won't have time for it until sometime in May.

Fine by me, I guess most of us are busy with the TPAMI SI anyway.

**Comment by mfeurer** [comment]
This was added in #922
