### ISSUE TITLE
Raise warning if sklearn model already fitted prior to _run_model_on_task/fold()

### ISSUE THREAD

**Issue by Neeratyoy** [openml/openml-python#968]
#### Description

Give a warning if model is already fitted.
This is acceptable in case of custom experimentation, but not desirable if we want to upload to OpenML. For transparent interpretation of OpenML results, the user should be told of what's happening.

Can be checked for in the `_run_model_on_fold()` function in `openml.extensions.sklearn.extension` prior to calling of `model_copy.fit()`.

Possible solutions:
* https://stackoverflow.com/a/39900933/8363967
* https://scikit-learn.org/stable/modules/generated/sklearn.utils.validation.check_is_fitted.html

**Comment by Neeratyoy** [comment]
Based on this line [here](https://github.com/openml/openml-python/blob/develop/openml/extensions/sklearn/extension.py#L1646) and the documentation of [clone](https://scikit-learn.org/stable/modules/generated/sklearn.base.clone.html) which suggests a new estimator _that has not been fitted_ is being created, this issue is rendered moot right?

I have got a branch locally that fixes this issue, but it appears it is just redundant code, so hence will push only if you feel we should still have an explicit check.

@mfeurer @PGijsbers

**Comment by PGijsbers** [comment]
To me it looks like the intention of this message is that if `_run_model_on_fold` is called with a model that is already fit, a warning should be raised *because* the model that is already fit is ignored and a new one is trained instead. This might not be what the user intended when they provided an already fit model to this function. But @mfeurer wrote this message and the code, so I'm interested to hear if I interpreted this correctly 😉

**Comment by mfeurer** [comment]
Sorry, could you please fill me in which message you are talking about? We should add a message which warns if the estimator is already fitted. There are scikit-learn helpers for checking that.

**Comment by PGijsbers** [comment]
Closed by #989
